[alias]
cef-build-simple-debug = "run --bin cef-build --release -- --profile dev --example simple"
cef-build-simple-release = "run --bin cef-build --release -- --profile release --example simple"
cef-build-windowless-debug = "run --bin cef-build --release -- --profile dev --example windowless"
cef-build-windowless-release = "run --bin cef-build --release -- --profile release --example windowless"
cef-clean = "run --bin cef-clean --release"
cef-artifacts = "run --bin cef-artifacts --release"

[env]
CEF_WORKSPACE_DIR = { relative = true, force = true, value = "" }
CEF_ARTIFACTS_DIR = { relative = true, force = true, value = "artifacts" }
